package com.vasnatech.commons.mimetype;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

public final class MimeTypeFactory {

    Map<String, Set<String>> allMimeTypes = new LinkedHashMap<>();

    private MimeTypeFactory() {
        allMimeTypes.put("application/vnd.lotus-1-2-3", Set.of("123"));
        allMimeTypes.put("text/vnd.in3d.3dml", Set.of("3dml"));
        allMimeTypes.put("video/3gpp2", Set.of("3g2"));
        allMimeTypes.put("image/avif", Set.of("avif"));
        allMimeTypes.put("image/avif-sequence", Set.of("avifs"));
        allMimeTypes.put("application/x-krita", Set.of("kra", "krz"));
        allMimeTypes.put("image/heic", Set.of("heif", "heic"));
        allMimeTypes.put("video/3gpp", Set.of("3gp"));
        allMimeTypes.put("audio/3gpp2", Set.of("3g2"));
        allMimeTypes.put("application/x-7z-compressed", Set.of("7z"));
        allMimeTypes.put("application/octet-stream", Set.of("a", "bin", "bpk", "deploy", "dist", "distz", "dmg", "dms", "dump", "elc", "lha", "lrf", "lzh", "o", "obj", "pkg", "so"));
        allMimeTypes.put("application/x-authorware-bin", Set.of("aab", "u32", "vox", "x32"));
        allMimeTypes.put("image/x-icns", Set.of("icns"));
        allMimeTypes.put("audio/mp4", Set.of("mp4", "m4a", "m4b", "m4p", "m4r", "m4v", "mp4v", "3gp", "3g2", "3ga", "3gpa", "3gpp", "3gpp2", "3gp2"));
        allMimeTypes.put("audio/aac", Set.of("aac", "m4a"));
        allMimeTypes.put("audio/mp4a-latm", Set.of());
        allMimeTypes.put("audio/aacp", Set.of("aacp"));
        allMimeTypes.put("application/x-authorware-map", Set.of("aam"));
        allMimeTypes.put("application/x-authorware-seg", Set.of("aas"));
        allMimeTypes.put("application/x-abiword", Set.of("abw", "zabw", "abw.gz"));
        allMimeTypes.put("application/vnd.americandynamics.acc", Set.of("acc"));
        allMimeTypes.put("application/x-ace-compressed", Set.of("ace"));
        allMimeTypes.put("application/vnd.acucobol", Set.of("acu"));
        allMimeTypes.put("application/vnd.acucorp", Set.of("acutc", "atc"));
        allMimeTypes.put("audio/adpcm", Set.of("adp"));
        allMimeTypes.put("application/vnd.audiograph", Set.of("aep"));
        allMimeTypes.put("application/x-font-type1", Set.of("afm", "pfa", "pfb", "pfm"));
        allMimeTypes.put("application/vnd.ibm.modcap", Set.of("afp", "list3820", "listafp"));
        allMimeTypes.put("application/postscript", Set.of("ai", "eps", "ps"));
        allMimeTypes.put("application/vnd.adobe.air-application-installer-package+zip", Set.of("air"));
        allMimeTypes.put("application/vnd.amiga.ami", Set.of("ami"));
        allMimeTypes.put("application/vnd.android.package-archive", Set.of("apk"));
        allMimeTypes.put("application/x-ms-application", Set.of("application"));
        allMimeTypes.put("application/vnd.lotus-approach", Set.of("apr"));
        allMimeTypes.put("application/pgp-signature", Set.of("asc", "sig"));
        allMimeTypes.put("video/x-ms-asf", Set.of("asf", "asx"));
        allMimeTypes.put("text/x-asm", Set.of("asm", "s"));
        allMimeTypes.put("application/vnd.accpac.simply.aso", Set.of("aso"));
        allMimeTypes.put("application/atom+xml", Set.of("atom"));
        allMimeTypes.put("application/atomcat+xml", Set.of("atomcat"));
        allMimeTypes.put("application/atomsvc+xml", Set.of("atomsvc"));
        allMimeTypes.put("application/vnd.antix.game-component", Set.of("atx"));
        allMimeTypes.put("audio/basic", Set.of("au", "snd"));
        allMimeTypes.put("video/x-msvideo", Set.of("avi"));
        allMimeTypes.put("application/applixware", Set.of("aw"));
        allMimeTypes.put("application/vnd.airzip.filesecure.azf", Set.of("azf"));
        allMimeTypes.put("application/vnd.airzip.filesecure.azs", Set.of("azs"));
        allMimeTypes.put("application/vnd.amazon.ebook", Set.of("azw"));
        allMimeTypes.put("application/x-msdownload", Set.of("bat", "com", "dll", "exe", "msi"));
        allMimeTypes.put("application/x-bcpio", Set.of("bcpio"));
        allMimeTypes.put("application/x-font-bdf", Set.of("bdf"));
        allMimeTypes.put("application/vnd.syncml.dm+wbxml", Set.of("bdm"));
        allMimeTypes.put("application/vnd.fujitsu.oasysprs", Set.of("bh2"));
        allMimeTypes.put("application/vnd.bmi", Set.of("bmi"));
        allMimeTypes.put("image/bmp", Set.of("bmp"));
        allMimeTypes.put("application/vnd.framemaker", Set.of("book", "fm", "frame", "maker"));
        allMimeTypes.put("application/vnd.previewsystems.box", Set.of("box"));
        allMimeTypes.put("application/x-bzip2", Set.of("boz", "bz2"));
        allMimeTypes.put("image/prs.btif", Set.of("btif"));
        allMimeTypes.put("application/x-bzip", Set.of("bz"));
        allMimeTypes.put("text/x-c", Set.of("c", "cc", "cpp", "cxx", "dic", "h", "hh"));
        allMimeTypes.put("application/vnd.clonk.c4group", Set.of("c4d", "c4f", "c4g", "c4p", "c4u"));
        allMimeTypes.put("application/vnd.ms-cab-compressed", Set.of("cab"));
        allMimeTypes.put("application/vnd.curl.car", Set.of("car"));
        allMimeTypes.put("application/vnd.ms-pki.seccat", Set.of("cat"));
        allMimeTypes.put("application/x-director", Set.of("cct", "cst", "cxt", "dcr", "dir", "dxr", "fgd", "swa", "w3d"));
        allMimeTypes.put("application/ccxml+xml", Set.of("ccxml"));
        allMimeTypes.put("application/vnd.contact.cmsg", Set.of("cdbcmsg"));
        allMimeTypes.put("application/x-netcdf", Set.of("cdf", "nc"));
        allMimeTypes.put("application/vnd.mediastation.cdkey", Set.of("cdkey"));
        allMimeTypes.put("chemical/x-cdx", Set.of("cdx"));
        allMimeTypes.put("application/vnd.chemdraw+xml", Set.of("cdxml"));
        allMimeTypes.put("application/vnd.cinderella", Set.of("cdy"));
        allMimeTypes.put("application/pkix-cert", Set.of("cer"));
        allMimeTypes.put("image/cgm", Set.of("cgm"));
        allMimeTypes.put("application/x-chat", Set.of("chat"));
        allMimeTypes.put("application/vnd.ms-htmlhelp", Set.of("chm"));
        allMimeTypes.put("application/vnd.kde.kchart", Set.of("chrt"));
        allMimeTypes.put("chemical/x-cif", Set.of("cif"));
        allMimeTypes.put("application/vnd.anser-web-certificate-issue-initiation", Set.of("cii"));
        allMimeTypes.put("application/vnd.ms-artgalry", Set.of("cil"));
        allMimeTypes.put("application/vnd.claymore", Set.of("cla"));
        allMimeTypes.put("application/java-vm", Set.of("class"));
        allMimeTypes.put("application/vnd.crick.clicker.keyboard", Set.of("clkk"));
        allMimeTypes.put("application/vnd.crick.clicker.palette", Set.of("clkp"));
        allMimeTypes.put("application/vnd.crick.clicker.template", Set.of("clkt"));
        allMimeTypes.put("application/vnd.crick.clicker.wordbank", Set.of("clkw"));
        allMimeTypes.put("application/vnd.crick.clicker", Set.of("clkx"));
        allMimeTypes.put("application/x-msclip", Set.of("clp"));
        allMimeTypes.put("application/vnd.cosmocaller", Set.of("cmc"));
        allMimeTypes.put("chemical/x-cmdf", Set.of("cmdf"));
        allMimeTypes.put("chemical/x-cml", Set.of("cml"));
        allMimeTypes.put("application/vnd.yellowriver-custom-menu", Set.of("cmp"));
        allMimeTypes.put("image/x-cmx", Set.of("cmx"));
        allMimeTypes.put("application/vnd.rim.cod", Set.of("cod"));
        allMimeTypes.put("text/plain", Set.of("conf", "def", "diff", "in", "ksh", "list", "log", "pl", "text", "txt"));
        allMimeTypes.put("application/vnd.debian.binary-package", Set.of("deb", "udeb"));
        allMimeTypes.put("text/markdown", Set.of("md", "markdown", "mdown", "markdn"));
        allMimeTypes.put("application/wasm", Set.of("wasm"));
        allMimeTypes.put("application/x-cpio", Set.of("cpio"));
        allMimeTypes.put("application/mac-compactpro", Set.of("cpt"));
        allMimeTypes.put("application/x-mscardfile", Set.of("crd"));
        allMimeTypes.put("application/pkix-crl", Set.of("crl"));
        allMimeTypes.put("application/x-x509-ca-cert", Set.of("crt", "der"));
        allMimeTypes.put("application/x-csh", Set.of("csh"));
        allMimeTypes.put("chemical/x-csml", Set.of("csml"));
        allMimeTypes.put("application/vnd.commonspace", Set.of("csp"));
        allMimeTypes.put("text/css", Set.of("css"));
        allMimeTypes.put("text/csv", Set.of("csv"));
        allMimeTypes.put("application/cu-seeme", Set.of("cu"));
        allMimeTypes.put("text/vnd.curl", Set.of("curl"));
        allMimeTypes.put("application/prs.cww", Set.of("cww"));
        allMimeTypes.put("application/vnd.mobius.daf", Set.of("daf"));
        allMimeTypes.put("application/vnd.fdsn.seed", Set.of("dataless", "seed"));
        allMimeTypes.put("application/davmount+xml", Set.of("davmount"));
        allMimeTypes.put("text/vnd.curl.dcurl", Set.of("dcurl"));
        allMimeTypes.put("application/vnd.oma.dd2+xml", Set.of("dd2"));
        allMimeTypes.put("application/vnd.fujixerox.ddd", Set.of("ddd"));
        allMimeTypes.put("application/x-debian-package", Set.of("deb", "udeb"));
        allMimeTypes.put("application/vnd.dreamfactory", Set.of("dfac"));
        allMimeTypes.put("application/vnd.mobius.dis", Set.of("dis"));
        allMimeTypes.put("image/vnd.djvu", Set.of("djv", "djvu"));
        allMimeTypes.put("application/vnd.dna", Set.of("dna"));
        allMimeTypes.put("application/msword", Set.of("doc", "dot", "wiz"));
        allMimeTypes.put("application/vnd.ms-word.document.macroenabled.12", Set.of("docm"));
        allMimeTypes.put("application/vnd.openxmlformats-officedocument.wordprocessingml.document", Set.of("docx"));
        allMimeTypes.put("application/vnd.ms-word.template.macroenabled.12", Set.of("dotm"));
        allMimeTypes.put("application/vnd.openxmlformats-officedocument.wordprocessingml.template", Set.of("dotx"));
        allMimeTypes.put("application/vnd.osgi.dp", Set.of("dp"));
        allMimeTypes.put("application/vnd.dpgraph", Set.of("dpg"));
        allMimeTypes.put("text/prs.lines.tag", Set.of("dsc"));
        allMimeTypes.put("application/x-dtbook+xml", Set.of("dtb"));
        allMimeTypes.put("application/xml-dtd", Set.of("dtd"));
        allMimeTypes.put("audio/vnd.dts", Set.of("dts"));
        allMimeTypes.put("audio/vnd.dts.hd", Set.of("dtshd"));
        allMimeTypes.put("application/x-dvi", Set.of("dvi"));
        allMimeTypes.put("model/vnd.dwf", Set.of("dwf"));
        allMimeTypes.put("image/vnd.dwg", Set.of("dwg"));
        allMimeTypes.put("image/vnd.dxf", Set.of("dxf"));
        allMimeTypes.put("application/vnd.spotfire.dxp", Set.of("dxp"));
        allMimeTypes.put("audio/vnd.nuera.ecelp4800", Set.of("ecelp4800"));
        allMimeTypes.put("audio/vnd.nuera.ecelp7470", Set.of("ecelp7470"));
        allMimeTypes.put("audio/vnd.nuera.ecelp9600", Set.of("ecelp9600"));
        allMimeTypes.put("application/ecmascript", Set.of("ecma"));
        allMimeTypes.put("application/vnd.novadigm.edm", Set.of("edm"));
        allMimeTypes.put("application/vnd.novadigm.edx", Set.of("edx"));
        allMimeTypes.put("application/vnd.picsel", Set.of("efif"));
        allMimeTypes.put("application/vnd.pg.osasli", Set.of("ei6"));
        allMimeTypes.put("message/rfc822", Set.of("eml", "mht", "mhtml", "mime", "nws"));
        allMimeTypes.put("application/emma+xml", Set.of("emma"));
        allMimeTypes.put("audio/vnd.digital-winds", Set.of("eol"));
        allMimeTypes.put("application/vnd.ms-fontobject", Set.of("eot"));
        allMimeTypes.put("application/epub+zip", Set.of("epub"));
        allMimeTypes.put("application/vnd.eszigno3+xml", Set.of("es3", "et3"));
        allMimeTypes.put("application/vnd.epson.esf", Set.of("esf"));
        allMimeTypes.put("text/x-setext", Set.of("etx"));
        allMimeTypes.put("application/vnd.novadigm.ext", Set.of("ext"));
        allMimeTypes.put("application/andrew-inset", Set.of("ez"));
        allMimeTypes.put("application/vnd.ezpix-album", Set.of("ez2"));
        allMimeTypes.put("application/vnd.ezpix-package", Set.of("ez3"));
        allMimeTypes.put("text/x-fortran", Set.of("f", "f77", "f90", "for"));
        allMimeTypes.put("video/x-f4v", Set.of("f4v"));
        allMimeTypes.put("image/vnd.fastbidsheet", Set.of("fbs"));
        allMimeTypes.put("application/vnd.fdf", Set.of("fdf"));
        allMimeTypes.put("application/vnd.denovo.fcselayout-link", Set.of("fe_launch"));
        allMimeTypes.put("application/vnd.fujitsu.oasysgp", Set.of("fg5"));
        allMimeTypes.put("image/x-freehand", Set.of("fh", "fh4", "fh5", "fh7", "fhc"));
        allMimeTypes.put("application/x-xfig", Set.of("fig"));
        allMimeTypes.put("video/x-fli", Set.of("fli"));
        allMimeTypes.put("application/vnd.micrografx.flo", Set.of("flo"));
        allMimeTypes.put("video/x-flv", Set.of("flv"));
        allMimeTypes.put("application/vnd.kde.kivio", Set.of("flw"));
        allMimeTypes.put("text/vnd.fmi.flexstor", Set.of("flx"));
        allMimeTypes.put("text/vnd.fly", Set.of("fly"));
        allMimeTypes.put("application/vnd.frogans.fnc", Set.of("fnc"));
        allMimeTypes.put("image/vnd.fpx", Set.of("fpx"));
        allMimeTypes.put("application/vnd.fsc.weblaunch", Set.of("fsc"));
        allMimeTypes.put("image/vnd.fst", Set.of("fst"));
        allMimeTypes.put("application/vnd.fluxtime.clip", Set.of("ftc"));
        allMimeTypes.put("application/vnd.anser-web-funds-transfer-initiation", Set.of("fti"));
        allMimeTypes.put("video/vnd.fvt", Set.of("fvt"));
        allMimeTypes.put("application/vnd.fuzzysheet", Set.of("fzs"));
        allMimeTypes.put("image/g3fax", Set.of("g3"));
        allMimeTypes.put("application/vnd.groove-account", Set.of("gac"));
        allMimeTypes.put("model/vnd.gdl", Set.of("gdl"));
        allMimeTypes.put("application/vnd.dynageo", Set.of("geo"));
        allMimeTypes.put("application/vnd.geometry-explorer", Set.of("gex", "gre"));
        allMimeTypes.put("application/vnd.geogebra.file", Set.of("ggb"));
        allMimeTypes.put("application/vnd.geogebra.tool", Set.of("ggt"));
        allMimeTypes.put("application/vnd.groove-help", Set.of("ghf"));
        allMimeTypes.put("image/gif", Set.of("gif"));
        allMimeTypes.put("application/vnd.groove-identity-message", Set.of("gim"));
        allMimeTypes.put("application/vnd.gmx", Set.of("gmx"));
        allMimeTypes.put("application/x-gnumeric", Set.of("gnumeric"));
        allMimeTypes.put("application/vnd.flographit", Set.of("gph"));
        allMimeTypes.put("application/vnd.grafeq", Set.of("gqf", "gqs"));
        allMimeTypes.put("application/srgs", Set.of("gram"));
        allMimeTypes.put("application/vnd.groove-injector", Set.of("grv"));
        allMimeTypes.put("application/srgs+xml", Set.of("grxml"));
        allMimeTypes.put("application/x-font-ghostscript", Set.of("gsf"));
        allMimeTypes.put("application/x-gtar", Set.of("gtar"));
        allMimeTypes.put("application/vnd.groove-tool-message", Set.of("gtm"));
        allMimeTypes.put("model/vnd.gtw", Set.of("gtw"));
        allMimeTypes.put("text/vnd.graphviz", Set.of("gv"));
        allMimeTypes.put("application/x-gzip", Set.of("gz", "tgz"));
        allMimeTypes.put("application/gzip", Set.of("gz", "tgz"));
        allMimeTypes.put("video/h261", Set.of("h261"));
        allMimeTypes.put("gcode", Set.of("gcode"));
        allMimeTypes.put("video/h263", Set.of("h263"));
        allMimeTypes.put("video/h264", Set.of("h264"));
        allMimeTypes.put("application/vnd.hbci", Set.of("hbci"));
        allMimeTypes.put("application/vnd.gerber", Set.of("gbr"));
        allMimeTypes.put("application/x-hdf", Set.of("hdf"));
        allMimeTypes.put("application/winhlp", Set.of("hlp"));
        allMimeTypes.put("application/vnd.hp-hpgl", Set.of("hpgl"));
        allMimeTypes.put("application/vnd.hp-hpid", Set.of("hpid"));
        allMimeTypes.put("application/vnd.hp-hps", Set.of("hps"));
        allMimeTypes.put("application/mac-binhex40", Set.of("hqx"));
        allMimeTypes.put("application/vnd.kenameaapp", Set.of("htke"));
        allMimeTypes.put("text/html", Set.of("htm", "html"));
        allMimeTypes.put("application/vnd.yamaha.hv-dic", Set.of("hvd"));
        allMimeTypes.put("application/vnd.yamaha.hv-voice", Set.of("hvp"));
        allMimeTypes.put("application/vnd.yamaha.hv-script", Set.of("hvs"));
        allMimeTypes.put("application/vnd.iccprofile", Set.of("icc", "icm"));
        allMimeTypes.put("x-conference/x-cooltalk", Set.of("ice"));
        allMimeTypes.put("image/x-icon", Set.of("ico"));
        allMimeTypes.put("text/calendar", Set.of("ics", "ifb"));
        allMimeTypes.put("image/ief", Set.of("ief"));
        allMimeTypes.put("application/vnd.shana.informed.formdata", Set.of("ifm"));
        allMimeTypes.put("model/iges", Set.of("iges", "igs"));
        allMimeTypes.put("application/vnd.igloader", Set.of("igl"));
        allMimeTypes.put("application/vnd.micrografx.igx", Set.of("igx"));
        allMimeTypes.put("application/vnd.shana.informed.interchange", Set.of("iif"));
        allMimeTypes.put("application/vnd.accpac.simply.imp", Set.of("imp"));
        allMimeTypes.put("application/vnd.ms-ims", Set.of("ims"));
        allMimeTypes.put("application/vnd.shana.informed.package", Set.of("ipk"));
        allMimeTypes.put("application/vnd.ibm.rights-management", Set.of("irm"));
        allMimeTypes.put("application/vnd.irepository.package+xml", Set.of("irp"));
        allMimeTypes.put("application/vnd.shana.informed.formtemplate", Set.of("itp"));
        allMimeTypes.put("application/vnd.immervision-ivp", Set.of("ivp"));
        allMimeTypes.put("application/vnd.immervision-ivu", Set.of("ivu"));
        allMimeTypes.put("text/vnd.sun.j2me.app-descriptor", Set.of("jad"));
        allMimeTypes.put("application/vnd.jam", Set.of("jam"));
        allMimeTypes.put("application/java-archive", Set.of("jar"));
        allMimeTypes.put("text/x-java-source", Set.of("java"));
        allMimeTypes.put("application/vnd.jisp", Set.of("jisp"));
        allMimeTypes.put("application/vnd.hp-jlyt", Set.of("jlt"));
        allMimeTypes.put("application/x-java-jnlp-file", Set.of("jnlp"));
        allMimeTypes.put("application/vnd.joost.joda-archive", Set.of("joda"));
        allMimeTypes.put("image/jpeg", Set.of("jpe", "jpeg", "jpg", "pjpg", "jfif", "jfif-tbnl", "jif"));
        allMimeTypes.put("image/pjpeg", Set.of("jpe", "jpeg", "jpg", "pjpg", "jfi", "jfif", "jfif-tbnl", "jif"));
        allMimeTypes.put("video/jpm", Set.of("jpgm", "jpm"));
        allMimeTypes.put("video/jpeg", Set.of("jpgv"));
        allMimeTypes.put("application/x-trash", Set.of());
        allMimeTypes.put("application/x-shellscript", Set.of("sh"));
        allMimeTypes.put("text/javascript", Set.of("js"));
        allMimeTypes.put("application/json", Set.of("json"));
        allMimeTypes.put("audio/midi", Set.of("kar", "mid", "midi", "rmi"));
        allMimeTypes.put("audio/aiff", Set.of("aiff", "aif", "aff"));
        allMimeTypes.put("audio/opus", Set.of("opus"));
        allMimeTypes.put("application/vnd.kde.karbon", Set.of("karbon"));
        allMimeTypes.put("application/vnd.kde.kformula", Set.of("kfo"));
        allMimeTypes.put("application/vnd.kidspiration", Set.of("kia"));
        allMimeTypes.put("application/x-killustrator", Set.of("kil"));
        allMimeTypes.put("application/vnd.google-earth.kml+xml", Set.of("kml"));
        allMimeTypes.put("application/vnd.google-earth.kmz", Set.of("kmz"));
        allMimeTypes.put("application/vnd.kinar", Set.of("kne", "knp"));
        allMimeTypes.put("application/vnd.kde.kontour", Set.of("kon"));
        allMimeTypes.put("application/vnd.kde.kpresenter", Set.of("kpr", "kpt"));
        allMimeTypes.put("application/vnd.kde.kspread", Set.of("ksp"));
        allMimeTypes.put("application/vnd.kahootz", Set.of("ktr", "ktz"));
        allMimeTypes.put("application/vnd.kde.kword", Set.of("kwd", "kwt"));
        allMimeTypes.put("application/x-latex", Set.of("latex"));
        allMimeTypes.put("application/vnd.llamagraphics.life-balance.desktop", Set.of("lbd"));
        allMimeTypes.put("application/vnd.llamagraphics.life-balance.exchange+xml", Set.of("lbe"));
        allMimeTypes.put("application/vnd.hhe.lesson-player", Set.of("les"));
        allMimeTypes.put("application/vnd.route66.link66+xml", Set.of("link66"));
        allMimeTypes.put("application/lost+xml", Set.of("lostxml"));
        allMimeTypes.put("application/vnd.ms-lrm", Set.of("lrm"));
        allMimeTypes.put("application/vnd.frogans.ltf", Set.of("ltf"));
        allMimeTypes.put("audio/vnd.lucent.voice", Set.of("lvp"));
        allMimeTypes.put("application/vnd.lotus-wordpro", Set.of("lwp"));
        allMimeTypes.put("application/x-msmediaview", Set.of("m13", "m14", "mvb"));
        allMimeTypes.put("video/mpeg", Set.of("m1v", "m2v", "mpa", "mpe", "mpeg", "mpg"));
        allMimeTypes.put("audio/mpeg", Set.of("m2a", "m3a", "mp2", "mp2a", "mp3", "mpga"));
        allMimeTypes.put("audio/x-mpegurl", Set.of("m3u"));
        allMimeTypes.put("video/vnd.mpegurl", Set.of("m4u", "mxu"));
        allMimeTypes.put("video/x-m4v", Set.of("m4v"));
        allMimeTypes.put("application/mathematica", Set.of("ma", "mb", "nb"));
        allMimeTypes.put("application/vnd.ecowin.chart", Set.of("mag"));
        allMimeTypes.put("text/troff", Set.of("man", "me", "ms", "roff", "t", "tr"));
        allMimeTypes.put("application/mathml+xml", Set.of("mathml", "mml"));
        allMimeTypes.put("text/mathml", Set.of("mathml", "mml"));
        allMimeTypes.put("application/vnd.sqlite3", Set.of("db", "sqlite", "sqlite3", "db-wal", "sqlite-wal", "db-shm", "sqlite-shm"));
        allMimeTypes.put("application/vnd.mobius.mbk", Set.of("mbk"));
        allMimeTypes.put("application/mbox", Set.of("mbox"));
        allMimeTypes.put("application/vnd.medcalcdata", Set.of("mc1"));
        allMimeTypes.put("application/vnd.mcd", Set.of("mcd"));
        allMimeTypes.put("text/vnd.curl.mcurl", Set.of("mcurl"));
        allMimeTypes.put("application/x-msaccess", Set.of("mdb"));
        allMimeTypes.put("image/vnd.ms-modi", Set.of("mdi"));
        allMimeTypes.put("model/mesh", Set.of("mesh", "msh", "silo"));
        allMimeTypes.put("application/vnd.mfmp", Set.of("mfm"));
        allMimeTypes.put("application/vnd.proteus.magazine", Set.of("mgz"));
        allMimeTypes.put("application/vnd.mif", Set.of("mif"));
        allMimeTypes.put("video/mj2", Set.of("mj2", "mjp2"));
        allMimeTypes.put("application/vnd.dolby.mlp", Set.of("mlp"));
        allMimeTypes.put("application/vnd.chipnuts.karaoke-mmd", Set.of("mmd"));
        allMimeTypes.put("application/vnd.smaf", Set.of("mmf"));
        allMimeTypes.put("image/vnd.fujixerox.edmics-mmr", Set.of("mmr"));
        allMimeTypes.put("application/x-msmoney", Set.of("mny"));
        allMimeTypes.put("application/x-mobipocket-ebook", Set.of("mobi", "prc"));
        allMimeTypes.put("video/quicktime", Set.of("mov", "qt"));
        allMimeTypes.put("video/x-sgi-movie", Set.of("movie"));
        allMimeTypes.put("video/mp4", Set.of("mp4", "mp4v", "mpg4"));
        allMimeTypes.put("application/x-iso9660-image", Set.of("iso", "isoimg", "cdr"));
        allMimeTypes.put("application/yaml", Set.of("yaml", "yml"));
        allMimeTypes.put("application/mp4", Set.of("mp4s"));
        allMimeTypes.put("application/vnd.mophun.certificate", Set.of("mpc"));
        allMimeTypes.put("application/vnd.apple.installer+xml", Set.of("mpkg"));
        allMimeTypes.put("application/vnd.blueice.multipass", Set.of("mpm"));
        allMimeTypes.put("application/vnd.mophun.application", Set.of("mpn"));
        allMimeTypes.put("application/vnd.ms-project", Set.of("mpp", "mpt"));
        allMimeTypes.put("application/vnd.ibm.minipay", Set.of("mpy"));
        allMimeTypes.put("application/vnd.mobius.mqy", Set.of("mqy"));
        allMimeTypes.put("application/marc", Set.of("mrc"));
        allMimeTypes.put("application/mediaservercontrol+xml", Set.of("mscml"));
        allMimeTypes.put("application/vnd.fdsn.mseed", Set.of("mseed"));
        allMimeTypes.put("application/vnd.mseq", Set.of("mseq"));
        allMimeTypes.put("application/vnd.epson.msf", Set.of("msf"));
        allMimeTypes.put("application/vnd.mobius.msl", Set.of("msl"));
        allMimeTypes.put("application/vnd.muvee.style", Set.of("msty"));
        allMimeTypes.put("model/vnd.mts", Set.of("mts"));
        allMimeTypes.put("application/vnd.musician", Set.of("mus"));
        allMimeTypes.put("application/vnd.recordare.musicxml+xml", Set.of("musicxml"));
        allMimeTypes.put("application/vnd.mfer", Set.of("mwf"));
        allMimeTypes.put("application/mxf", Set.of("mxf"));
        allMimeTypes.put("application/vnd.recordare.musicxml", Set.of("mxl"));
        allMimeTypes.put("application/xv+xml", Set.of("mxml", "xhvml", "xvm", "xvml"));
        allMimeTypes.put("application/vnd.triscape.mxs", Set.of("mxs"));
        allMimeTypes.put("application/vnd.nokia.n-gage.symbian.install", Set.of("n-gage"));
        allMimeTypes.put("application/x-dtbncx+xml", Set.of("ncx"));
        allMimeTypes.put("application/vnd.nokia.n-gage.data", Set.of("ngdat"));
        allMimeTypes.put("application/vnd.neurolanguage.nlu", Set.of("nlu"));
        allMimeTypes.put("application/vnd.enliven", Set.of("nml"));
        allMimeTypes.put("application/vnd.noblenet-directory", Set.of("nnd"));
        allMimeTypes.put("application/vnd.noblenet-sealer", Set.of("nns"));
        allMimeTypes.put("application/vnd.noblenet-web", Set.of("nnw"));
        allMimeTypes.put("image/vnd.net-fpx", Set.of("npx"));
        allMimeTypes.put("application/vnd.lotus-notes", Set.of("nsf"));
        allMimeTypes.put("application/vnd.fujitsu.oasys2", Set.of("oa2"));
        allMimeTypes.put("application/vnd.fujitsu.oasys3", Set.of("oa3"));
        allMimeTypes.put("application/vnd.fujitsu.oasys", Set.of("oas"));
        allMimeTypes.put("application/x-msbinder", Set.of("obd"));
        allMimeTypes.put("application/oda", Set.of("oda"));
        allMimeTypes.put("application/vnd.oasis.opendocument.database", Set.of("odb"));
        allMimeTypes.put("application/vnd.oasis.opendocument.chart", Set.of("odc"));
        allMimeTypes.put("application/vnd.oasis.opendocument.formula", Set.of("odf"));
        allMimeTypes.put("application/vnd.oasis.opendocument.formula-template", Set.of("odft"));
        allMimeTypes.put("application/vnd.oasis.opendocument.graphics", Set.of("odg"));
        allMimeTypes.put("application/vnd.oasis.opendocument.image", Set.of("odi"));
        allMimeTypes.put("application/vnd.oasis.opendocument.presentation", Set.of("odp"));
        allMimeTypes.put("application/vnd.oasis.opendocument.spreadsheet", Set.of("ods"));
        allMimeTypes.put("application/vnd.oasis.opendocument.text", Set.of("odt"));
        allMimeTypes.put("audio/ogg", Set.of("oga", "ogg", "spx"));
        allMimeTypes.put("video/x-matroska", Set.of("mkv"));
        allMimeTypes.put("audio/x-matroska", Set.of("mka"));
        allMimeTypes.put("video/ogg", Set.of("ogv"));
        allMimeTypes.put("application/ogg", Set.of("ogx"));
        allMimeTypes.put("application/onenote", Set.of("onepkg", "onetmp", "onetoc", "onetoc2"));
        allMimeTypes.put("application/oebps-package+xml", Set.of("opf"));
        allMimeTypes.put("application/vnd.palm", Set.of("oprc", "pdb", "pqa"));
        allMimeTypes.put("application/vnd.lotus-organizer", Set.of("org"));
        allMimeTypes.put("application/vnd.yamaha.openscoreformat", Set.of("osf"));
        allMimeTypes.put("application/vnd.yamaha.openscoreformat.osfpvg+xml", Set.of("osfpvg"));
        allMimeTypes.put("application/vnd.oasis.opendocument.chart-template", Set.of("otc"));
        allMimeTypes.put("font/woff", Set.of("woff"));
        allMimeTypes.put("font/woff2", Set.of("woff2"));
        allMimeTypes.put("application/x-redhat-package-manager", Set.of("rpa"));
        allMimeTypes.put("application/x-perl", Set.of("pm", "pl"));
        allMimeTypes.put("audio/webm", Set.of("weba"));
        allMimeTypes.put("video/webm", Set.of("webm"));
        allMimeTypes.put("image/webp", Set.of("webp"));
        allMimeTypes.put("application/x-font-otf", Set.of("otf"));
        allMimeTypes.put("font/otf", Set.of("otf"));
        allMimeTypes.put("application/vnd.oasis.opendocument.graphics-template", Set.of("otg"));
        allMimeTypes.put("application/vnd.oasis.opendocument.text-web", Set.of("oth"));
        allMimeTypes.put("application/vnd.oasis.opendocument.image-template", Set.of("oti"));
        allMimeTypes.put("application/vnd.oasis.opendocument.text-master", Set.of("otm"));
        allMimeTypes.put("application/vnd.oasis.opendocument.presentation-template", Set.of("otp"));
        allMimeTypes.put("application/vnd.oasis.opendocument.spreadsheet-template", Set.of("ots"));
        allMimeTypes.put("application/vnd.oasis.opendocument.text-template", Set.of("ott"));
        allMimeTypes.put("application/vnd.openofficeorg.extension", Set.of("oxt"));
        allMimeTypes.put("text/x-pascal", Set.of("p", "pas", "pp", "inc"));
        allMimeTypes.put("application/pkcs10", Set.of("p10"));
        allMimeTypes.put("application/x-pkcs12", Set.of("p12", "pfx"));
        allMimeTypes.put("application/x-pkcs7-certificates", Set.of("p7b", "spc"));
        allMimeTypes.put("application/pkcs7-mime", Set.of("p7c", "p7m"));
        allMimeTypes.put("application/x-pkcs7-certreqresp", Set.of("p7r"));
        allMimeTypes.put("application/pkcs7-signature", Set.of("p7s"));
        allMimeTypes.put("application/vnd.powerbuilder6", Set.of("pbd"));
        allMimeTypes.put("image/x-portable-bitmap", Set.of("pbm"));
        allMimeTypes.put("application/x-font-pcf", Set.of("pcf"));
        allMimeTypes.put("application/vnd.hp-pcl", Set.of("pcl"));
        allMimeTypes.put("application/vnd.hp-pclxl", Set.of("pclxl"));
        allMimeTypes.put("image/x-pict", Set.of("pct", "pic"));
        allMimeTypes.put("application/vnd.curl.pcurl", Set.of("pcurl"));
        allMimeTypes.put("image/x-pcx", Set.of("pcx"));
        allMimeTypes.put("application/pdf", Set.of("pdf"));
        allMimeTypes.put("application/font-tdpfr", Set.of("pfr"));
        allMimeTypes.put("image/x-portable-graymap", Set.of("pgm"));
        allMimeTypes.put("application/x-chess-pgn", Set.of("pgn"));
        allMimeTypes.put("application/pgp-encrypted", Set.of("pgp"));
        allMimeTypes.put("application/pkixcmp", Set.of("pki"));
        allMimeTypes.put("application/pkix-pkipath", Set.of("pkipath"));
        allMimeTypes.put("application/vnd.3gpp.pic-bw-large", Set.of("plb"));
        allMimeTypes.put("application/vnd.mobius.plc", Set.of("plc"));
        allMimeTypes.put("application/vnd.pocketlearn", Set.of("plf"));
        allMimeTypes.put("application/pls+xml", Set.of("pls"));
        allMimeTypes.put("application/vnd.ctc-posml", Set.of("pml"));
        allMimeTypes.put("image/png", Set.of("png"));
        allMimeTypes.put("image/x-portable-anymap", Set.of("pnm"));
        allMimeTypes.put("application/vnd.macports.portpkg", Set.of("portpkg"));
        allMimeTypes.put("application/vnd.ms-powerpoint", Set.of("pot", "ppa", "pps", "ppt", "pwz"));
        allMimeTypes.put("application/vnd.ms-powerpoint.template.macroenabled.12", Set.of("potm"));
        allMimeTypes.put("application/vnd.openxmlformats-officedocument.presentationml.template", Set.of("potx"));
        allMimeTypes.put("application/vnd.ms-powerpoint.addin.macroenabled.12", Set.of("ppam"));
        allMimeTypes.put("application/vnd.cups-ppd", Set.of("ppd"));
        allMimeTypes.put("image/x-portable-pixmap", Set.of("ppm"));
        allMimeTypes.put("application/vnd.ms-powerpoint.slideshow.macroenabled.12", Set.of("ppsm"));
        allMimeTypes.put("application/vnd.openxmlformats-officedocument.presentationml.slideshow", Set.of("ppsx"));
        allMimeTypes.put("application/vnd.ms-powerpoint.presentation.macroenabled.12", Set.of("pptm"));
        allMimeTypes.put("application/vnd.openxmlformats-officedocument.presentationml.presentation", Set.of("pptx"));
        allMimeTypes.put("application/vnd.lotus-freelance", Set.of("pre"));
        allMimeTypes.put("application/pics-rules", Set.of("prf"));
        allMimeTypes.put("application/prql", Set.of("prql"));
        allMimeTypes.put("application/vnd.3gpp.pic-bw-small", Set.of("psb"));
        allMimeTypes.put("image/vnd.adobe.photoshop", Set.of("psd"));
        allMimeTypes.put("application/x-font-linux-psf", Set.of("psf"));
        allMimeTypes.put("application/vnd.pvi.ptid1", Set.of("ptid"));
        allMimeTypes.put("application/x-mspublisher", Set.of("pub"));
        allMimeTypes.put("application/vnd.3gpp.pic-bw-var", Set.of("pvb"));
        allMimeTypes.put("application/vnd.3m.post-it-notes", Set.of("pwn"));
        allMimeTypes.put("text/x-python", Set.of("py", "pyc", "pyo", "pyd", "whl"));
        allMimeTypes.put("audio/vnd.ms-playready.media.pya", Set.of("pya"));
        allMimeTypes.put("video/vnd.ms-playready.media.pyv", Set.of("pyv"));
        allMimeTypes.put("application/vnd.epson.quickanime", Set.of("qam"));
        allMimeTypes.put("application/vnd.intu.qbo", Set.of("qbo"));
        allMimeTypes.put("application/vnd.intu.qfx", Set.of("qfx"));
        allMimeTypes.put("application/vnd.publishare-delta-tree", Set.of("qps"));
        allMimeTypes.put("application/vnd.quark.quarkxpress", Set.of("qwd", "qwt", "qxb", "qxd", "qxl", "qxt"));
        allMimeTypes.put("audio/x-pn-realaudio", Set.of("ra", "ram"));
        allMimeTypes.put("application/vnd.rar", Set.of("rar"));
        allMimeTypes.put("application/x-rar-compressed", Set.of("rar"));
        allMimeTypes.put("image/x-cmu-raster", Set.of("ras"));
        allMimeTypes.put("application/vnd.ipunplugged.rcprofile", Set.of("rcprofile"));
        allMimeTypes.put("application/rdf+xml", Set.of("rdf"));
        allMimeTypes.put("application/vnd.data-vision.rdz", Set.of("rdz"));
        allMimeTypes.put("application/vnd.businessobjects", Set.of("rep"));
        allMimeTypes.put("application/x-dtbresource+xml", Set.of("res"));
        allMimeTypes.put("image/x-rgb", Set.of("rgb"));
        allMimeTypes.put("application/reginfo+xml", Set.of("rif"));
        allMimeTypes.put("application/resource-lists+xml", Set.of("rl"));
        allMimeTypes.put("image/vnd.fujixerox.edmics-rlc", Set.of("rlc"));
        allMimeTypes.put("application/resource-lists-diff+xml", Set.of("rld"));
        allMimeTypes.put("application/vnd.rn-realmedia", Set.of("rm"));
        allMimeTypes.put("audio/x-pn-realaudio-plugin", Set.of("rmp"));
        allMimeTypes.put("application/vnd.jcp.javame.midlet-rms", Set.of("rms"));
        allMimeTypes.put("application/relax-ng-compact-syntax", Set.of("rnc"));
        allMimeTypes.put("application/x-rpm", Set.of("rpm"));
        allMimeTypes.put("application/vnd.nokia.radio-presets", Set.of("rpss"));
        allMimeTypes.put("application/vnd.nokia.radio-preset", Set.of("rpst"));
        allMimeTypes.put("application/sparql-query", Set.of("rq"));
        allMimeTypes.put("application/rls-services+xml", Set.of("rs"));
        allMimeTypes.put("application/rsd+xml", Set.of("rsd"));
        allMimeTypes.put("application/rss+xml", Set.of("rss", "xml"));
        allMimeTypes.put("application/rtf", Set.of("rtf"));
        allMimeTypes.put("text/richtext", Set.of("rtx"));
        allMimeTypes.put("application/vnd.yamaha.smaf-audio", Set.of("saf"));
        allMimeTypes.put("application/sbml+xml", Set.of("sbml"));
        allMimeTypes.put("application/vnd.ibm.secure-container", Set.of("sc"));
        allMimeTypes.put("application/x-msschedule", Set.of("scd"));
        allMimeTypes.put("application/vnd.lotus-screencam", Set.of("scm"));
        allMimeTypes.put("application/scvp-cv-request", Set.of("scq"));
        allMimeTypes.put("application/scvp-cv-response", Set.of("scs"));
        allMimeTypes.put("text/vnd.curl.scurl", Set.of("scurl"));
        allMimeTypes.put("application/vnd.stardivision.draw", Set.of("sda"));
        allMimeTypes.put("application/vnd.stardivision.calc", Set.of("sdc"));
        allMimeTypes.put("application/vnd.stardivision.impress", Set.of("sdd"));
        allMimeTypes.put("application/vnd.solent.sdkm+xml", Set.of("sdkd", "sdkm"));
        allMimeTypes.put("application/sdp", Set.of("sdp"));
        allMimeTypes.put("application/vnd.stardivision.writer", Set.of("sdw", "vor"));
        allMimeTypes.put("application/vnd.seemail", Set.of("see"));
        allMimeTypes.put("application/vnd.sema", Set.of("sema"));
        allMimeTypes.put("application/vnd.semd", Set.of("semd"));
        allMimeTypes.put("application/vnd.semf", Set.of("semf"));
        allMimeTypes.put("application/java-serialized-object", Set.of("ser"));
        allMimeTypes.put("application/set-payment-initiation", Set.of("setpay"));
        allMimeTypes.put("application/set-registration-initiation", Set.of("setreg"));
        allMimeTypes.put("application/vnd.hydrostatix.sof-data", Set.of("sfd-hdstx"));
        allMimeTypes.put("application/vnd.spotfire.sfs", Set.of("sfs"));
        allMimeTypes.put("application/vnd.stardivision.writer-global", Set.of("sgl"));
        allMimeTypes.put("text/sgml", Set.of("sgm", "sgml"));
        allMimeTypes.put("application/x-sh", Set.of("sh"));
        allMimeTypes.put("application/x-shar", Set.of("shar"));
        allMimeTypes.put("application/shf+xml", Set.of("shf"));
        allMimeTypes.put("text/vnd.wap.si", Set.of("si"));
        allMimeTypes.put("application/vnd.wap.sic", Set.of("sic"));
        allMimeTypes.put("application/vnd.symbian.install", Set.of("sis", "sisx"));
        allMimeTypes.put("application/x-stuffit", Set.of("sit"));
        allMimeTypes.put("application/x-stuffitx", Set.of("sitx"));
        allMimeTypes.put("application/vnd.koan", Set.of("skd", "skm", "skp", "skt"));
        allMimeTypes.put("text/vnd.wap.sl", Set.of("sl"));
        allMimeTypes.put("application/vnd.wap.slc", Set.of("slc"));
        allMimeTypes.put("application/vnd.ms-powerpoint.slide.macroenabled.12", Set.of("sldm"));
        allMimeTypes.put("application/vnd.openxmlformats-officedocument.presentationml.slide", Set.of("sldx"));
        allMimeTypes.put("application/vnd.epson.salt", Set.of("slt"));
        allMimeTypes.put("application/vnd.stardivision.math", Set.of("smf"));
        allMimeTypes.put("application/smil+xml", Set.of("smi", "smil"));
        allMimeTypes.put("application/x-font-snf", Set.of("snf"));
        allMimeTypes.put("application/vnd.yamaha.smaf-phrase", Set.of("spf"));
        allMimeTypes.put("application/x-futuresplash", Set.of("spl"));
        allMimeTypes.put("text/vnd.in3d.spot", Set.of("spot"));
        allMimeTypes.put("application/scvp-vp-response", Set.of("spp"));
        allMimeTypes.put("application/scvp-vp-request", Set.of("spq"));
        allMimeTypes.put("application/x-wais-source", Set.of("src"));
        allMimeTypes.put("application/sparql-results+xml", Set.of("srx"));
        allMimeTypes.put("application/vnd.kodak-descriptor", Set.of("sse"));
        allMimeTypes.put("application/vnd.epson.ssf", Set.of("ssf"));
        allMimeTypes.put("application/ssml+xml", Set.of("ssml"));
        allMimeTypes.put("application/vnd.sun.xml.calc.template", Set.of("stc"));
        allMimeTypes.put("application/vnd.sun.xml.draw.template", Set.of("std"));
        allMimeTypes.put("application/vnd.wt.stf", Set.of("stf"));
        allMimeTypes.put("application/vnd.sun.xml.impress.template", Set.of("sti"));
        allMimeTypes.put("application/hyperstudio", Set.of("stk"));
        allMimeTypes.put("application/vnd.ms-pki.stl", Set.of("stl"));
        allMimeTypes.put("application/vnd.pg.format", Set.of("str"));
        allMimeTypes.put("application/vnd.sun.xml.writer.template", Set.of("stw"));
        allMimeTypes.put("application/vnd.sus-calendar", Set.of("sus", "susp"));
        allMimeTypes.put("application/x-sv4cpio", Set.of("sv4cpio"));
        allMimeTypes.put("application/x-sv4crc", Set.of("sv4crc"));
        allMimeTypes.put("application/vnd.svd", Set.of("svd"));
        allMimeTypes.put("image/svg+xml", Set.of("svg", "svgz"));
        allMimeTypes.put("application/x-shockwave-flash", Set.of("swf"));
        allMimeTypes.put("application/vnd.arastra.swi", Set.of("swi"));
        allMimeTypes.put("application/vnd.sun.xml.calc", Set.of("sxc"));
        allMimeTypes.put("application/vnd.sun.xml.draw", Set.of("sxd"));
        allMimeTypes.put("application/vnd.sun.xml.writer.global", Set.of("sxg"));
        allMimeTypes.put("application/vnd.sun.xml.impress", Set.of("sxi"));
        allMimeTypes.put("application/vnd.sun.xml.math", Set.of("sxm"));
        allMimeTypes.put("application/vnd.sun.xml.writer", Set.of("sxw"));
        allMimeTypes.put("application/vnd.tao.intent-module-archive", Set.of("tao"));
        allMimeTypes.put("application/x-tar", Set.of("tar"));
        allMimeTypes.put("application/vnd.3gpp2.tcap", Set.of("tcap"));
        allMimeTypes.put("application/x-tcl", Set.of("tcl"));
        allMimeTypes.put("application/vnd.smart.teacher", Set.of("teacher"));
        allMimeTypes.put("application/x-tex", Set.of("tex"));
        allMimeTypes.put("application/x-texinfo", Set.of("texi", "texinfo"));
        allMimeTypes.put("application/x-tex-tfm", Set.of("tfm"));
        allMimeTypes.put("image/tiff", Set.of("tif", "tiff"));
        allMimeTypes.put("application/vnd.tmobile-livetv", Set.of("tmo"));
        allMimeTypes.put("application/x-bittorrent", Set.of("torrent"));
        allMimeTypes.put("application/vnd.groove-tool-template", Set.of("tpl"));
        allMimeTypes.put("application/vnd.trid.tpt", Set.of("tpt"));
        allMimeTypes.put("application/vnd.trueapp", Set.of("tra"));
        allMimeTypes.put("application/x-msterminal", Set.of("trm"));
        allMimeTypes.put("text/tab-separated-values", Set.of("tsv"));
        allMimeTypes.put("application/x-font-ttf", Set.of("ttc", "ttf"));
        allMimeTypes.put("application/vnd.simtech-mindmapper", Set.of("twd", "twds"));
        allMimeTypes.put("application/vnd.genomatix.tuxedo", Set.of("txd"));
        allMimeTypes.put("application/vnd.mobius.txf", Set.of("txf"));
        allMimeTypes.put("application/vnd.ufdl", Set.of("ufd", "ufdl"));
        allMimeTypes.put("test/mimetype", Set.of("test"));
        allMimeTypes.put("application/vnd.umajin", Set.of("umj"));
        allMimeTypes.put("application/vnd.unity", Set.of("unityweb"));
        allMimeTypes.put("application/vnd.uoml+xml", Set.of("uoml"));
        allMimeTypes.put("text/uri-list", Set.of("uri", "uris", "urls"));
        allMimeTypes.put("application/x-ustar", Set.of("ustar"));
        allMimeTypes.put("application/vnd.uiq.theme", Set.of("utz"));
        allMimeTypes.put("text/x-uuencode", Set.of("uu"));
        allMimeTypes.put("application/x-cdlink", Set.of("vcd"));
        allMimeTypes.put("text/x-vcard", Set.of("vcf"));
        allMimeTypes.put("application/vnd.groove-vcard", Set.of("vcg"));
        allMimeTypes.put("text/x-vcalendar", Set.of("vcs"));
        allMimeTypes.put("application/vnd.vcx", Set.of("vcx"));
        allMimeTypes.put("application/vnd.visionary", Set.of("vis"));
        allMimeTypes.put("video/vnd.vivo", Set.of("viv"));
        allMimeTypes.put("model/vrml", Set.of("vrml", "wrl"));
        allMimeTypes.put("application/vnd.visio", Set.of("vsd", "vss", "vst", "vsw", "vsdx", "vssx", "vstx", "vssm", "vstm"));
        allMimeTypes.put("application/vnd.vsf", Set.of("vsf"));
        allMimeTypes.put("model/vnd.vtu", Set.of("vtu"));
        allMimeTypes.put("application/voicexml+xml", Set.of("vxml"));
        allMimeTypes.put("application/x-doom", Set.of("wad"));
        allMimeTypes.put("video/mp2t", Set.of("ts"));
        allMimeTypes.put("audio/vnd.wav", Set.of("wav"));
        allMimeTypes.put("audio/x-ms-wax", Set.of("wax"));
        allMimeTypes.put("image/vnd.wap.wbmp", Set.of("wbmp"));
        allMimeTypes.put("application/vnd.criticaltools.wbs+xml", Set.of("wbs"));
        allMimeTypes.put("application/vnd.wap.wbxml", Set.of("wbxml"));
        allMimeTypes.put("application/vnd.ms-works", Set.of("wcm", "wdb", "wks", "wps"));
        allMimeTypes.put("video/x-ms-wm", Set.of("wm"));
        allMimeTypes.put("audio/x-ms-wma", Set.of("wma"));
        allMimeTypes.put("application/x-ms-wmd", Set.of("wmd"));
        allMimeTypes.put("application/x-msmetafile", Set.of("wmf"));
        allMimeTypes.put("text/vnd.wap.wml", Set.of("wml"));
        allMimeTypes.put("application/vnd.wap.wmlc", Set.of("wmlc"));
        allMimeTypes.put("text/vnd.wap.wmlscript", Set.of("wmls"));
        allMimeTypes.put("application/vnd.wap.wmlscriptc", Set.of("wmlsc"));
        allMimeTypes.put("video/x-ms-wmv", Set.of("wmv"));
        allMimeTypes.put("video/x-ms-wmx", Set.of("wmx"));
        allMimeTypes.put("application/x-ms-wmz", Set.of("wmz"));
        allMimeTypes.put("application/vnd.wordperfect", Set.of("wpd"));
        allMimeTypes.put("application/vnd.ms-wpl", Set.of("wpl"));
        allMimeTypes.put("application/vnd.wqd", Set.of("wqd"));
        allMimeTypes.put("application/x-mswrite", Set.of("wri"));
        allMimeTypes.put("application/wsdl+xml", Set.of("wsdl"));
        allMimeTypes.put("application/wspolicy+xml", Set.of("wspolicy"));
        allMimeTypes.put("application/vnd.webturbo", Set.of("wtb"));
        allMimeTypes.put("video/x-ms-wvx", Set.of("wvx"));
        allMimeTypes.put("application/vnd.hzn-3d-crossword", Set.of("x3d"));
        allMimeTypes.put("application/x-silverlight-app", Set.of("xap"));
        allMimeTypes.put("application/vnd.xara", Set.of("xar"));
        allMimeTypes.put("application/x-ms-xbap", Set.of("xbap"));
        allMimeTypes.put("application/vnd.fujixerox.docuworks.binder", Set.of("xbd"));
        allMimeTypes.put("image/x-xbitmap", Set.of("xbm"));
        allMimeTypes.put("application/vnd.syncml.dm+xml", Set.of("xdm"));
        allMimeTypes.put("application/vnd.adobe.xdp+xml", Set.of("xdp"));
        allMimeTypes.put("application/vnd.fujixerox.docuworks", Set.of("xdw"));
        allMimeTypes.put("application/xenc+xml", Set.of("xenc"));
        allMimeTypes.put("application/patch-ops-error+xml", Set.of("xer"));
        allMimeTypes.put("application/vnd.adobe.xfdf", Set.of("xfdf"));
        allMimeTypes.put("application/vnd.xfdl", Set.of("xfdl"));
        allMimeTypes.put("application/xhtml+xml", Set.of("xht", "xhtml"));
        allMimeTypes.put("image/vnd.xiff", Set.of("xif"));
        allMimeTypes.put("application/vnd.ms-excel", Set.of("xla", "xlb", "xlc", "xlm", "xls", "xlt", "xlw"));
        allMimeTypes.put("application/vnd.ms-excel.addin.macroenabled.12", Set.of("xlam"));
        allMimeTypes.put("application/vnd.ms-excel.sheet.binary.macroenabled.12", Set.of("xlsb"));
        allMimeTypes.put("application/vnd.ms-excel.sheet.macroenabled.12", Set.of("xlsm"));
        allMimeTypes.put("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Set.of("xlsx"));
        allMimeTypes.put("application/vnd.ms-excel.template.macroenabled.12", Set.of("xltm"));
        allMimeTypes.put("application/vnd.openxmlformats-officedocument.spreadsheetml.template", Set.of("xltx"));
        allMimeTypes.put("application/xml", Set.of("xml", "xpdl", "xsl"));
        allMimeTypes.put("application/vnd.olpc-sugar", Set.of("xo"));
        allMimeTypes.put("application/xop+xml", Set.of("xop"));
        allMimeTypes.put("application/x-xpinstall", Set.of("xpi"));
        allMimeTypes.put("image/x-xpixmap", Set.of("xpm"));
        allMimeTypes.put("application/vnd.is-xpr", Set.of("xpr"));
        allMimeTypes.put("application/vnd.ms-xpsdocument", Set.of("xps"));
        allMimeTypes.put("application/vnd.intercon.formnet", Set.of("xpw", "xpx"));
        allMimeTypes.put("application/xslt+xml", Set.of("xslt"));
        allMimeTypes.put("application/vnd.syncml+xml", Set.of("xsm"));
        allMimeTypes.put("application/xspf+xml", Set.of("xspf"));
        allMimeTypes.put("application/vnd.mozilla.xul+xml", Set.of("xul"));
        allMimeTypes.put("image/x-xwindowdump", Set.of("xwd"));
        allMimeTypes.put("chemical/x-xyz", Set.of("xyz"));
        allMimeTypes.put("application/vnd.zzazz.deck+xml", Set.of("zaz"));
        allMimeTypes.put("application/zip", Set.of("zip"));
        allMimeTypes.put("application/x-zip-compressed", Set.of("zip"));
        allMimeTypes.put("application/zip-compressed", Set.of("zip"));
        allMimeTypes.put("application/vnd.zul", Set.of("zir", "zirz"));
        allMimeTypes.put("application/vnd.handheld-entertainment+xml", Set.of("zmm"));
        allMimeTypes.put("image/x-adobe-dng", Set.of("dng"));
        allMimeTypes.put("image/x-sony-arw", Set.of("arw"));
        allMimeTypes.put("image/x-canon-cr2", Set.of("cr2"));
        allMimeTypes.put("image/x-canon-crw", Set.of("crw"));
        allMimeTypes.put("image/x-kodak-dcr", Set.of("dcr"));
        allMimeTypes.put("image/x-epson-erf", Set.of("erf"));
        allMimeTypes.put("image/x-kodak-k25", Set.of("k25"));
        allMimeTypes.put("image/x-kodak-kdc", Set.of("kdc"));
        allMimeTypes.put("image/x-minolta-mrw", Set.of("mrw"));
        allMimeTypes.put("image/x-nikon-nef", Set.of("nef"));
        allMimeTypes.put("image/x-olympus-orf", Set.of("orf"));
        allMimeTypes.put("image/x-pentax-pef", Set.of("pef", "ptx"));
        allMimeTypes.put("image/x-fuji-raf", Set.of("raf"));
        allMimeTypes.put("image/x-panasonic-raw", Set.of("raw", "rw2", "rwl"));
        allMimeTypes.put("audio/flac", Set.of("flac"));
        allMimeTypes.put("image/x-sony-sr2", Set.of("sr2"));
        allMimeTypes.put("image/x-sony-srf", Set.of("srf"));
        allMimeTypes.put("image/x-sigma-x3f", Set.of("x3f"));
    }

    public MimeType create(String mimeType) {
        Set<String> fileTypes = allMimeTypes.get(mimeType);
        if (fileTypes == null) {
            throw new IllegalArgumentException("Unknown mime type: " + mimeType);
        }
        return new MimeType(mimeType, fileTypes);
    }
}